// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_Qyi6n121muo9KsxocK0BuuCQx95bw4',
    appId: '1:387582085828:web:7d36904e5182f4bc0c1791',
    messagingSenderId: '387582085828',
    projectId: 'admin-panel-14c21',
    authDomain: 'admin-panel-14c21.firebaseapp.com',
    storageBucket: 'admin-panel-14c21.firebasestorage.app',
    measurementId: 'G-277BPMKQZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc1a0z5n4BK3nKg0--WHJUNwmtP1KPlPI',
    appId: '1:387582085828:android:5bd6ba8c45a4052b0c1791',
    messagingSenderId: '387582085828',
    projectId: 'admin-panel-14c21',
    storageBucket: 'admin-panel-14c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm_2ITomOe4ETmVTo2Wicd00SxO6eOMDg',
    appId: '1:387582085828:ios:231d0061eb6102090c1791',
    messagingSenderId: '387582085828',
    projectId: 'admin-panel-14c21',
    storageBucket: 'admin-panel-14c21.firebasestorage.app',
    iosBundleId: 'com.tht.portfolio.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm_2ITomOe4ETmVTo2Wicd00SxO6eOMDg',
    appId: '1:387582085828:ios:231d0061eb6102090c1791',
    messagingSenderId: '387582085828',
    projectId: 'admin-panel-14c21',
    storageBucket: 'admin-panel-14c21.firebasestorage.app',
    iosBundleId: 'com.tht.portfolio.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn_Qyi6n121muo9KsxocK0BuuCQx95bw4',
    appId: '1:387582085828:web:ede4e7ec828fdf780c1791',
    messagingSenderId: '387582085828',
    projectId: 'admin-panel-14c21',
    authDomain: 'admin-panel-14c21.firebaseapp.com',
    storageBucket: 'admin-panel-14c21.firebasestorage.app',
    measurementId: 'G-X91BVPDWBK',
  );
}
